### ISSUE TITLE
Why package name changed from `grpc-cpp` to `grpcio`?

### ISSUE THREAD

**Issue by corneliusroemer** [conda-forge/grpc-cpp-feedstock#291]
### Comment:

It seems that you stopped publishing packages named `grpc-cpp` with version `grpc-cpp 1.51.1  h88f4db0_3 conda-forge/osx-64`

Versions higher than that seem to be only installable via `grpcio`, e.g. `grpcio 1.54.1  py39h840bb9f_0    conda-forge/osx-64`. The change to no longer publish `grpc-cpp` seems to have been made around this commit: https://github.com/conda-forge/grpc-cpp-feedstock/commit/bd4e5a2e0b56ee2aac78d10c65b85e0640193871

What's the reason for this? This seems to cause some problems:
- Some other package in my environment seems to require `grpc-cpp`
- Instead of this being a clear version conflict, it appears as follows in `mamba`'s repoquery:
```
The following packages are incompatible
├─ grpc-cpp   is requested and can be installed;
├─ jax 0.4.8**  is installable and it requires
│  └─ jaxlib >=0.4.7  with the potential options
│     ├─ jaxlib 0.4.7 would require
│     │  ├─ libgrpc >=1.52.1,<1.53.0a0 , which requires
│     │  │  └─ grpc-cpp 1.52.1* , which conflicts with any installable versions previously reported;
│     │  └─ openssl >=3.1.0,<4.0a0 , which can be installed;
│     ├─ jaxlib 0.4.7 would require
│     │  ├─ libgrpc >=1.54.0,<1.55.0a0  but there are no viable options
│     │  │  ├─ libgrpc 1.54.1 would require
│     │  │  │  └─ grpc-cpp 1.54.1* , which conflicts with any installable versions previously reported;
│     │  │  └─ libgrpc 1.54.0 would require
│     │  │     └─ grpc-cpp 1.54.0* , which conflicts with any installable versions previously reported;
```

**Comment by h-vetinari** [comment]
`grpcio` wasn't touched, it was `grpc-cpp` that was renamed to `libgrpc` in https://github.com/conda-forge/grpc-cpp-feedstock/pull/245 for 1.49, and the old output was removed in https://github.com/conda-forge/grpc-cpp-feedstock/pull/266 for 1.52.

So that matches what you are seeing, namely that after 1.51, there's no more grpc-cpp, only libgrpc. The solution is to not explicitly depend on `grpc-cpp`, and where you need only the C++ library (and not the python bindings in `grpcio`), then you need to rename your dependency to `libgrpc`.
