### ISSUE TITLE
Downstream issues with 1.55.0

### ISSUE THREAD

**Issue by bollwyvl** [conda-forge/grpc-cpp-feedstock#301]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Not sure if this is the right place for this but am seeing some issues with `155.0` on some python downstreams:

on https://github.com/conda-forge/grpcio-health-checking-feedstock/pull/37

```
    grpcio:                 1.55.0-py311ha6695c7_1      conda-forge
    libprotobuf:            4.23.2-hd1fb520_1           conda-forge


ImportError: $WORK_DIR/lib/python3.11/site-packages/google/protobuf/pyext/_message.cpython-311-x86_64-linux-gnu.so: undefined symbol: _ZN6google8protobuf2io17SafeDoubleToFloatEd
```

on https://github.com/conda-forge/dagster-feedstock/pull/259 ([logs](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=712528&view=logs&j=ad423587-88ab-5f41-8939-ac449515395d&t=1d262d2d-668a-5fdf-be81-cd412c29af64&l=2947))

```
    grpcio:                 1.55.0-py311ha6695c7_0      conda-forge
    grpcio-health-checking: 1.54.2-pyhd8ed1ab_0         conda-forge
    libprotobuf:            4.23.2-hd1fb520_0           conda-forge
 
ImportError: libprotobuf.so.23.1.0: cannot open shared object file: No such file or directory
```

### Installed packages

```shell
See above
```

### Environment info

```shell
See above
```

**Comment by h-vetinari** [comment]
First one is https://github.com/conda-forge/protobuf-feedstock/issues/190, investigation ongoing, help welcome

Second one is [this](https://github.com/conda-forge/conda-forge-pinning-feedstock/issues/4075#issuecomment-1564484062), which is solved by the new migrator. You can pin `libprotobuf >=4.23.2` to fix it, or if you really feel like it, add a repodata patch for that grpc build to use libprotobuf 4.23.2 instead of .1.

**Comment by h-vetinari** [comment]
Both issues have now been resolved, so I'm closing this.

**Comment by bollwyvl** [comment]
Thank you!
